[package]
name = "powereg"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.178"
udev = "0.9.3"
clap = { version = "4.5.53", features = ["derive"] }

ratatui = "0.29.0"
color-eyre = "0.6.3"
crossterm = "0.28.1"
toml = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
